##numpy array and basics

In [1]:
import numpy as np

``````##Create array from list``````



In [ ]:
arr_1d=np.array([1,2,3,4,5])

print("1d array:",arr_1d )

arr_2d=np.array([[1,2,3],[4,5,6]])
for i in  arr_2d:{
    print(i)
   
}

# print("2d array:",arr_2d )

1d array: [1 2 3 4 5]
[1 2 3]
[4 5 6]
2


##list vs Numpy array

In [ ]:
py_list =[1,2,3]
print("python list multiplication ",py_list*2)

np_array=np.array([1,2,3]) #element wise multiplication
print("python array multiplication ",np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n list opeartion time: ",time.time()-start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n numpy  opeartion time: ",time.time()-start)


python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication  [2 4 6]

 list opeartion time:  0.06517839431762695

 numpy  opeartion time:  0.004313468933105469


##creating array from scratch

In [71]:
zeros= np.zeros((3,4))
print("zeros array :",zeros)

ones=np.ones((2,3))
print("ones array:\n",ones)

full=np.full((2,3),5)

print("full array:\n",full)

random= np.random.random((2,3))
print("random array:\n",random)

sequence=np.arange(0,10,2)
print("Sequence array:\n",sequence)

zeros array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[5 5 5]
 [5 5 5]]
random array:
 [[0.59438372 0.77280522 0.9076646 ]
 [0.53305541 0.75324871 0.04689225]]
Sequence array:
 [0 2 4 6 8]


##vector ,matrix  and Tensor 

In [ ]:

vector =np.array([1,2,3,4])
print("vector:\n",vector)

matrix =np.array([[1,2,3],
                  [4,5,6]])

print("matrix:\n",matrix)
print(type(matrix))

tensor=np.array([[[1,2,3],
                  [4,5,6],
                 [ 7,8,9]]])


print("tensor\n",tensor)


vector:
 [1 2 3 4]
matrix:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
1
2
3
4
tensor
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Array properties

In [93]:
arr=np.array([[1,2,3],
              [4,'f',6]])

print("size of array:\n",arr.size)
print("Dimension of array:\n",arr.ndim)
print("Shape of array:\n",arr.shape)
print("Data Type of array:",arr.dtype)


size of array:
 6
Dimension of array:
 2
Shape of array:
 (2, 3)
Data Type of array: <U21


Array Reshaping

In [105]:
arr=np.arange(12)
print("original array\n",arr)

reshaped=arr.reshape((2,2,3))
print("Reshaped array:\n",reshaped)

flattend=reshaped.flatten()
print("flattened array:\n",flattend)

# return view instaed of copy
raveled=reshaped.ravel()
print("Ravel array:",raveled)

# transpose
transposed=reshaped.T
print("Transpose array:\n", transposed)

original array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array:
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravel array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose array:
 [[[ 0  6]
  [ 3  9]]

 [[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]]


In [108]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])
a = arr.ravel()

a[0] = 100

print(arr)

[[100   2]
 [  3   4]]
