Numpy array Opeartion

In [19]:
import numpy as np

In [20]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing:\n",arr[2:7])
print("with step:\n",arr[1:8:2])
print("negative slicing:\n",arr[-3])

Basic Slicing:
 [3 4 5 6 7]
with step:
 [2 4 6 8]
negative slicing:
 7


In [21]:
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("specific element:\n",arr_2d[1,2])
print("Entire Row:\n",arr_2d[1])
print("Entire columns:\n",arr_2d[:,1])


specific element:
 6
Entire Row:
 [4 5 6]
Entire columns:
 [2 5 8]


Sorting

In [22]:
unsorted=np.array([1,5,4,3,2,8,9])
print("Sprted array:\n",np.sort(unsorted))

unsorted_arr_2d=np.array([[9,2,6],
                 [8,5,4],
                 [1,6,9]])

print("Soeted 2D array by Columns:\n",np.sort(unsorted_arr_2d,axis=0))
print("Soeted 2D array by row:\n",np.sort(unsorted_arr_2d,axis=1))

Sprted array:
 [1 2 3 4 5 8 9]
Soeted 2D array by Columns:
 [[1 2 4]
 [8 5 6]
 [9 6 9]]
Soeted 2D array by row:
 [[2 6 9]
 [4 5 8]
 [1 6 9]]


Filter

In [23]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers % 2==0]
print("Even NUmbers:\n",even_number)

Even NUmbers:
 [ 2  4  6  8 10]


Filter with mask

In [24]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
mask=numbers>5
print("In boolean expression :\n",mask)

print("Numbers less than 5 :\n",numbers[mask])

In boolean expression :
 [False False False False False  True  True  True  True  True]
Numbers less than 5 :
 [ 6  7  8  9 10]


Fancy Indexing  vs np.where()

In [25]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>6)
print(where_result)
print("np where:\n",numbers[where_result])

[1 3 5]
(array([6, 7, 8, 9]),)
np where:
 [ 7  8  9 10]


COnditional array

In [30]:
cond_array=np.where(numbers>5,numbers*2,numbers)
print("\n",cond_array)

numbers=np.array([1,2,3,4,5,6,7,8,9,10])
print("indices where elemnt >5:\n",np.where(numbers>5))


 [ 1 24  3 32]
indices where elemnt >5:
 (array([5, 6, 7, 8, 9]),)


In [ ]:
# same as where 
import numpy as np

numbers = np.array([1, 6, 3, 8])

for i in range(len(numbers)):
    if numbers[i] > 5:
        numbers[i] *= 2
    else:
        numbers[i] = numbers[i]

print(numbers)


[ 1 12  3 16]


Adding and removing data

In [35]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibity

In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("compability shape",a.shape==b.shape)

compability shape True


In [41]:
original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

wirh_new_row=np.vstack((original,new_row))
print("original array:\n",original)
print("with new row:\n",wirh_new_row)

new_columns=([[7],[8]])
with_new_columns=np.hstack((original,new_columns))
print("with new columns:\n",with_new_columns)

original array:
 [[1 2]
 [3 4]]
with new row:
 [[1 2]
 [3 4]
 [5 6]]
with new columns:
 [[1 2 7]
 [3 4 8]]


DElete

In [50]:
arr=np.array([1,2,3,4,5])
deleted=np.delete(arr,2)
# wher1=(np.where(arr==2)[0])
# print(wher1)
print(deleted)

[1 2 4 5]
